name: ebook_example_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
    sdk: '>=2.19.6 <3.0.0'

dependencies:
    ebook:
        path: ../../
    image: ^4.0.15
    intl: ^0.18.1
    path: ^1.8.3
    path_provider: ^2.0.14
    universal_io: ^2.2.0

dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.0
